-- Drop tables if they exist to start fresh
DROP TABLE IF EXISTS assignments;
DROP TABLE IF EXISTS campaigns;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS admins;

-- Create Admins Table
CREATE TABLE admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    status TEXT DEFAULT 'Active',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create Users Table
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    status TEXT DEFAULT 'Active',
    type TEXT DEFAULT 'Punch',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create Campaigns Table
CREATE TABLE campaigns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    offer_id TEXT,
    country TEXT,
    link TEXT,
    type TEXT DEFAULT 'Click',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create Assignments Table (User Campaigns)
CREATE TABLE assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    campaign_id BIGINT REFERENCES campaigns(id) ON DELETE CASCADE,
    count INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(user_id, campaign_id)
);

-- Insert Default Admin
INSERT INTO admins (name, email, password, status)
VALUES ('Deepmind', 'admin@admin.com', 'admin123', 'Active');
